version: "3.9"

networks:
  cfrdocarmo-network:
    driver: bridge

services:
  cfrdocarmo-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "13306:3306"
    networks:
      - cfrdocarmo-network

  cfrdocarmo-redis:
    image: redis:6.2.1-alpine
    networks:
      - cfrdocarmo-network


  cfrdocarmo-api:
    image: cfrdocarmo-api
    command: ["/wait-for-it.sh", "cfrdocarmofood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      S3-ID-KEY-ACSESS: AKIAUI5IYRPGZR7NOHP3
      s3-key-secret: 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
      DB_HOST: cfrdocarmo-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: cfrdocarmo-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - cfrdocarmo-network
    depends_on:
      - cfrdocarmo-mysql

  cfrdocarmo-proxy:
    build: ./nginx
    image: cfrdocarmo-proxy
    ports:
      - "80:80"
    networks:
      - cfrdocarmo-network
    depends_on:
      - cfrdocarmo-api
